version: '3'

services:
  mysql:
    image: mysql:8.0
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: Exsana-db
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    ports:
      - "6033:3306"
    volumes:
      - db-data:/var/lib/mysql
    networks:
      dev:
        aliases:
          - mysql
  
  web:
    build:
        context: ./docker
        dockerfile: Dockerfile
    ports:
        - "8000:80"
    volumes:
        - .:/var/www/html
    environment:
        - APP_ENV=dev
    networks:
        - dev

volumes:
  db-data:

networks:
  dev:
